server:
  port: 80

# 配置日志地址
logging:
  config: classpath:logback-spring.xml

spring:
  file-storage: #文件存储配置
    default-platform: minio-1 #默认使用的存储平台
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    minio: # MinIO，由于 MinIO SDK 支持 AWS S3，其它兼容 AWS S3 协议的存储平台也都可配置在这里
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: admin
        secret-key: password
        end-point: http://127.0.0.1:9001
        bucket-name: test
        domain: "http://127.0.0.1:9001/" # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: zhengqingya/ # 基础路径
