server:
  port: 80
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    threads:
      io: 16        # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程 （不要设置过大，如果过大，启动项目会报错：打开文件数过多）
      worker: 200   # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8

spring:
  application:
    name: demo

# 配置日志地址
logging:
  config: classpath:logback-spring.xml



